// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ughYDeqW7DIilF7WKFN795ccVabZggc',
    appId: '1:219668556742:web:f18fbec9602208168a20c7',
    messagingSenderId: '219668556742',
    projectId: 'my-chat-app-150b6',
    authDomain: 'my-chat-app-150b6.firebaseapp.com',
    storageBucket: 'my-chat-app-150b6.firebasestorage.app',
    measurementId: 'G-SVH75ZRLCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-WuNxr8huLts3ZTExL291IpCiEm3iE8',
    appId: '1:219668556742:android:bca6004cda37d3008a20c7',
    messagingSenderId: '219668556742',
    projectId: 'my-chat-app-150b6',
    storageBucket: 'my-chat-app-150b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX5HeYt8-hAmk1cdl1gD5L7D65iCDyy7o',
    appId: '1:219668556742:ios:6ab84e8625a1e9f18a20c7',
    messagingSenderId: '219668556742',
    projectId: 'my-chat-app-150b6',
    storageBucket: 'my-chat-app-150b6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX5HeYt8-hAmk1cdl1gD5L7D65iCDyy7o',
    appId: '1:219668556742:ios:6ab84e8625a1e9f18a20c7',
    messagingSenderId: '219668556742',
    projectId: 'my-chat-app-150b6',
    storageBucket: 'my-chat-app-150b6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7ughYDeqW7DIilF7WKFN795ccVabZggc',
    appId: '1:219668556742:web:46d6ac63c51419e38a20c7',
    messagingSenderId: '219668556742',
    projectId: 'my-chat-app-150b6',
    authDomain: 'my-chat-app-150b6.firebaseapp.com',
    storageBucket: 'my-chat-app-150b6.firebasestorage.app',
    measurementId: 'G-V5HK4VQ2ES',
  );
}
